### ISSUE TITLE
Feature: Possibility to pause/resume consumer

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#103]
Kafka offers the possibility to pause consumers. A paused consumer stays connected to the broker i.e. Partitions and hence there is no rebalance and it is light weight to pause/resume. 

Our use case is that we have heavy load on a database which is caused only by consuming from Kafka. From time to time we have to do some house keeping. This generates additional load to the database and due to this (as well as some necessary locking), sql commands are slower than usual or timeout. Our application can cope with this but it generates noise in the logs and it's an ugly default behavior. This could be solved by pause the consumers before executing the house keeping. As we can assume that there is no more load from the consumer we can also make us of higher locks which speed up the clean up. Win-win. 

The following screenshot shows the consumer API. Would it be possible to expose this beside the connect/disconnect?

![Screenshot_2020-08-07-15-25-23-824_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/7792779/89650784-38b79880-d8c3-11ea-8c23-c23a0efeaab6.jpg)

**Comment by BEagle1984** [comment]
This is surely an interesting feature but I don't think that `pause`/`resume` is what you need here. As far as I know (excuse my limited experience) `pause`/`resume` is used when you have to control the partitions priorities, deliberately pausing some partitions while still consuming others.
In your scenario, if I understood it correctly, you just want to stop the entire consumer (or even all consumers). In that case one can just avoid calling the `poll` method. That's also safer and easier to implement, since we may run into some edge cases like a rebalance happening while paused, that would in my opinion implicitly resume (the newly assigned partitions).

_First and foremost, did I get the use case correctly? Or do you need to pause each partition independently?_

Well, if we just stop polling there's actually the problem of the `max.poll.interval.ms` setting, that determines the maximum interval between the polling attempts before the broker considers the consumer stuck and reassigns its partitions.

_How long of a pause do you need to perform your housekeeping? Do you think you can live with increasing the max.poll.interval.ms?

I guess the pause is gonna be very short, if you are unwilling to disconnect the consumer to avoid the cost of a re-connection, isn't it?_

At the end of the day, it would maybe be better to use `pause` and keep polling, but I would like to simply expose the `Pause`/`Resume` methods (on the `IConsumer`, `IBroker` and `IBrokerCollection`) without parameters and keep controlling the partitions internally. I mean that I will probably call `pause` for all partitions and ensure that I pause again after a re-balance.

Let me know if my assumptions are correct and you agree with the proposed implementation.

**Comment by msallin** [comment]
> First and foremost, did I get the use case correctly? Or do you need to pause each partition independently?

Yes you did. I wan't to pause the whole consumer. But I can imagine that the pause of partitions will be required in the future.
Btw. we don't have this use case anymore... 

> How long of a pause do you need to perform your housekeeping? Do you think you can live with increasing the max.poll.interval.ms?

It is 5min by default. That would be okay.

> I guess the pause is gonna be very short, if you are unwilling to disconnect the consumer to avoid the cost of a re-connection, isn't it?

Yes and when you do in-memory stream processing then you have to do a lot of work on rebalances. Thus, pause/resume is faster and "cleaner"

> At the end of the day, it would maybe be better to use pause and keep polling, but I would like to simply expose the Pause/Resume methods (on the IConsumer, IBroker and IBrokerCollection) without parameters and keep controlling the partitions internally. I mean that I will probably call pause for all partitions and ensure that I pause again after a re-balance.

Sounds good. Currently there is no need to control it by partition.

**Comment by BEagle1984** [comment]
This is also already included in [v3.0.0-beta.streaming.5](https://github.com/BEagle1984/silverback/releases/tag/v3.0.0-beta.streaming.5).
The `IConsumer` now exposes a `Stop` and `Start` method that can be used to pause and resume the consumer.

I currently don't use `pause` and `resume` but I simply stop the consumer loop on my side. It should be fine for the discussed use case.
