### ISSUE TITLE
Feature: Add the possibility to give a name to Brokers

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#104]
Currently there is no way to uniquely identify a broker. Provide a property "name" which can be set.

Optional:
To make it more useful when building on top of it, give the guarantee that the name is unique. By default name it like the type of the broker and append a number (e.g. KafkaBroker-1) to make it unique.

**Comment by BEagle1984** [comment]
There's a misunderstanding here. As per the current implementation you will never have two `KafkaBroker` added to the collection. If you use  multiple Kafka clusters there's still gonna be only one `KafkaBroker` in the collection, with many consumers (and producers).
The message broker connection properties are defined in the endpoints, so each inbound/outbound endpoint you register could actually connect to a different cluster, but there still will be only one `KafkaBroker` instance.

You will only end up with multiple `IBroker` objects if you use different message brokers (e.g. `KafkaBroker` and `RabbitBroker`).

I guess you (we) are probably gonna stick to Kafka, therefore you could completely ignore the `IBrokerCollection` and resolve and work directly with the only `IBroker` being registered.
Note that each broker is also registered in the DI container as `IBroker` and the type itself, so you can resolve either `IBroker`, `KafkaBroker`, `IEnumerable<IBroker>` or of course `IBrokerCollection` and always access the same object. I suggest to work with the abstractions though, since you might want to swap `KafkaBroker` for `InMemoryBroker` in the tests.

That being said. Is my assumption correct that you will work with Kafka only? Do you think that a `Name` property would still be necessary?

By the way, slightly off topic, I just noticed that the `IBrokerCollection` was missing the indexer and I added it, so at least we can access the brokers via index instead of looping with LINQ...if somebody will ever use multiple brokers in the same application.

**Comment by msallin** [comment]
Ah, I understand. Thanks for your explanation.

We might gonna work with MQTT in the future. Maybe we will implement this for as Broker for Silverback, lets see...
But then the Type of the broker is enough and it is not necessary to have the name.
