### ISSUE TITLE
DDD and Domain Events - transactions and IntegrationMessages

### ISSUE THREAD

**Issue by igorgiovannini** [BEagle1984/silverback#123]
As an example, let's take the same scope as the one in the documentation (https://silverback-messaging.net/assets/beta/concepts/domain-events.html?tabs=entity):

-- Basket.cs
```csharp
public void Checkout()
{
	CheckoutDate = DateTime.UtcNow;
	AddEvent<BasketCheckoutEvent>();
}
```

-- BasketIntegrationEventsMapper.cs
```csharp
public IMessage OnBasketCheckoutEvent(BasketCheckoutEvent @event) =>
	new BasketCheckoutIntegrationEvent
	{
		Id = @event.Id,
		SomethingElse = "Bla bla bla"
	};
```

------------

Now let's suppose the code invokes the Checkout method for a Basket and then the changes are saved (SaveChanges method is invoked).

What happens:
1. Domain events are published;
2. Events are consumed (in that case, the BasketCheckoutEvent is consumed and mapped to an IntegrationEvent, and therefore is published to our message broker);
3. Maybe something goes wrong during the SaveChanges (SQL server not available? Or maybe XYZ happens);
4. Our message has been published to our message broker and something/someone can consume it, but in the meanwhile something went wrong previously on our side.

It would be better instead, that the IntegrationMessages are published only **if** the whole transaction was successful, otherwise you have to handle with proper policies the errors which can occur on the other side.
If someone else consumes our messages, this could be very misleading and confusing, because we are currently producing something which is not really what we have on our side.

A solution could be:
All the integration messages created in the scope of the transaction are temporarily saved, queued, and then, only if the transaction was successful (TransactionCompletedEvent), they are effectively produced.

**Comment by BEagle1984** [comment]
I know where you are coming from and I discussed this with Chris as well. :wink:
This is the intended behavior.
The domain events are published before the actual `SaveChanges` takes places because you could use them for different reasons than simply relaying them to the message broker. For example, you could have a subscriber that writes an audit every time certain events occur on your order and you obviously want your audit to be saved to the db as part of the same transaction (to prevent it to get lost).

If your concern is the transactionality of the `Produce` and the `SaveChanges`, then you should have a look at the outbox pattern:  https://silverback-messaging.net/assets/beta/concepts/broker/outbound.html#transactional-outbox-strategy. This would ensure consistency, at the cost of some added lag. (Note that this also works just because `SaveChanges` is called after the events have been processed.)

On the other hand, if you are just concerned about the timing issue you could simply retry the operation on the consumer side (e.g. using Polly) and wait for the data to be available.

**Comment by BEagle1984** [comment]
By the way, the outbox strategy is more or less the solution you are proposing, with a persistent storage (otherwise there's no guarantee that they will ever be produced).

**Comment by igorgiovannini** [comment]
Thanks for the answer Sergio ;-)
I'll call you in the next days about this topic...
