### ISSUE TITLE
Wrong partition assignment in `MockedConfluentProducer`

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#141]
Should https://github.com/BEagle1984/silverback/blob/387ef056511e74ee43ce043d3fef5d38e629f83e/src/Silverback.Integration.Kafka.Testing/Messaging/Broker/Kafka/Mocks/MockedConfluentProducer.cs#L156 

not be more like

```csharp
return messageKey.Aggregate(0, (sum, @byte) => sum + @byte) % topic.Partitions.Count;
```

**Comment by BEagle1984** [comment]
I thought it doesn't really matter so I went for the shortest implementation.
It think it doesn't matter because the key purpose is to ensure that the messages with the same key land in the same partition and that's being ensured by my very simplistic implementation. Yours might guarantee a bit better distribution in some cases but who cares?

Do you agree or do you think it's worth changing? (Well, if you send a PR I will approve it, as said it doesn't matter a lot to me. I have just been lazy here. 😝)

**Comment by msallin** [comment]
Ah yes.. You are right. The same key will get into the same partition. I made a thinking mistake while looking at this. Your approach works!
