### ISSUE TITLE
Question: EnsureExactlyOnce

### ISSUE THREAD

**Issue by soernt** [BEagle1984/silverback#144]
I look at the `ExactlyOnceTest.ExactlyOnce_DbInboundLog_DuplicatedMessagesIgnored`  and wounder about the KafkaEndpoint configuration: 
```c#
config.EnableAutoCommit = false;
config.CommitOffsetEach = 1;
```
When the message Id is stored for each consumed message within the "AddInboundLogDatabaseTable()"  table, why is it needed to disable auto commit and commit each message to Kafka? I would expect that configuration for the StoreOffsets strategy.

**Comment by BEagle1984** [comment]
Hi @soernt 

It's not needed. 😉 

That was just something I used to do in the tests to optimize their run time. Since I assert that the committed offset is the one I expect, I would have needed to wait until the auto commit took place (and the default auto commit interval is 5 seconds).
Now, in the latest versions of Silverback, I automatically override that interval to 50 milliseconds (if not otherwise configured) but I didn't clean up all the tests.

You can ignore it.

**Comment by soernt** [comment]
Thank you very much for the clarification!
