### ISSUE TITLE
Integration Testing Help

### ISSUE THREAD

**Issue by CeeJayCee** [BEagle1984/silverback#146]
Hello,

I'm looking for some guidance on how to integration test Silverback/Kafka when using an ASP.Net web project.

I'm trying to write a test for a web project that has a Silverback consumer and an HTTP controller. The HTTP controller responds with the last value it received from Kafka. The actual service is working correctly - I'm trying to write an integration test to prove it's all wired up correctly.

My question is: _how do I "fake" a Kafka message into the message bus?_

In my `Startup.cs - ConfigureServices()`:

```
	services.AddSilverback()
		.WithConnectionToMessageBroker(broker => broker.AddKafka())
		.AddEndpointsConfigurator<EndpointsConfigurator>()
		.AddSingletonSubscriber<MyConsumerHere>()
		.UseModel();
```
		
`EndpointsConfigurator`:

```
builder.AddKafkaEndpoints(
	endpoints =>
		endpoints.Configure(
			config => {
				config.BootstrapServers = "PLAINTEXT://mykafkahere:9092;
			}
		).AddInbound(endpoint =>
			endpoint.ConsumeFrom("incoming-data")
				.Configure(
					config => {
						config.GroupId = "my-handler";
						config.AutoOffsetReset = AutoOffsetReset.Latest;
					})
				.DeserializeJson(serializer => serializer.UseFixedType<MyMessageType>())
		)
	);
```
In my test file:
```
var factory = new WebApplicationFactory<Startup>().WithWebHostBuilder(
	builder => {
		builder.ConfigureTestServices(
			services => {
				services
					.ConfigureSilverback()
					.UseMockedKafka()
					.AddIntegrationSpy();
			}
	   );
	}
);

var helper = factory.Services.GetRequiredService<IKafkaTestingHelper>();
```
I have tried the following:
* Querying the helper for a producer:`helper.Broker.GetProducer("incoming-data")`
	* Error:  _"Sequence contains no matching element"_
* Creating a new producer `factory.Services.GetRequiredService<IBroker>().GetProducer(new  afkaProducerEndpoint("shortcode-new"));`
  * Error: _Silverback.Messaging.EndpointConfigurationException : BootstrapServers is required to connect with the message broker._
* Getting the `InMemoryTopic` directly from the helper, and pushing a message directly to it
  * No error, but the consumer never gets called.

Can you give me some guidance?

Thanks!

**Comment by BEagle1984** [comment]
Hi @CeeJayCee, that might seem a bit tricky but in reality it isn't.

It's correct that you want to get a producer instance to write the messages into the topic. This is what I do in my tests too.

`helper.Broker.GetProducer("incoming-data")` doesn't work because it simply searches for an existing configured producer with an endpoint matching that name. This works in the case where you have an outbound configured for that endpoint as well, but it isn't your case.
In order for Silverback to be able to build a new producer, you need to pass the entire `IProducerEndpoint` with all the needed settings.

In the project templates we use at Swiss Post I added the following extension method to help with building a producer on the fly.

```csharp
    public static class BrokerExtensions
    {
        public static IProducer GetTestProducer(this IBroker broker, string topicName)
        {
            var builder = new KafkaProducerEndpointBuilder();
            builder
                .ProduceTo(topicName)
                .Configure(config => config.BootstrapServers = "PLAINTEXT://tests");
            var endpoint = builder.Build();

            return broker.GetProducer(endpoint);
        }
    }
```

The above method cannot be built into Silverback directly because the endpoint configuration really depends upon the serializer you are using and other details.

What I planned for the future is to create an extension method like `GetProducerForCosumer(string endpointName)` that creates a matching `IProducerEndpoint` for the `IConsumerEndpoint` (of the inbound you registered) and would make the whole thing a lot easier. The only problem is the mapping that will need to be manually performed and redeveloped per each broker type (Kafka, MQTT, Rabbit). It isn't a big deal but I really didn't have the chance to work on it so far, because of different priorities.
For the time being, my suggestion is to create your own specific method like shown in the above snippet.

I hope this helps you get a step further.

**Comment by BEagle1984** [comment]
Sorry, forgot to mention a couple of things.

The extension method from the previous post would be used like `helper.Broker.GetTestProducer("your-topic")`.

Your attempt at calling `GetProducer` with the endpoint didn't work for the reason mentioned in the exception message: the broker name configuration is mandatory. The mock itself supports the case where multiple brokers (multiple Kafka clusters) are in place and without the `BootstrapServers` setting I wouldn't know to which one I should connect you.

Pushing directly to the `InMemoryTopic` should also work. I don't know why it didn't for you but I guess it's a timing issue that you will face with the producer as well.
If you connect with `AutoOffsetReset.Latest` (which is the default), it means that the consumer has to be connected to the broker before the message is pushed or it will not receive it. The `IKafkaHelper` gives you the tools to properly time your test.

```csharp
public async Task Test1()
{
    var factory = ...;
    var helper = factory.Services.GetRequiredService<IKafkaTestingHelper>();

    // Wait until the consumers are connected
    await helper.WaitUntilConnected();

    // Produce the test message
    var producer = helper.Broker.GetTestProducer("your-topic"); // Assuming you use the proposed extension method, otherwise you need to build an endpoint here (either using the builder or manually)
    await producer.ProduceAsync(new SomeMessage() { ... });

    // Wait until the consumer has processed all messages
    await helper.WaitUntilAllMessagesAreConsumedAsync();

    // Now you can assert!
}
```

**Comment by CeeJayCee** [comment]
Hi @BEagle1984,

Thanks for the explanation, tips and examples. I think I have previously tried various combinations of what you've written :-)

Unfortunately, my consumer is still not being called.

I have uploaded a slimmed down example here: https://github.com/CeeJayCee/SilverbackIntegrationTest

Would you mind telling me what I've done wrong?

Thanks!

**Comment by BEagle1984** [comment]
Sure, no problem. I dropped you a PR.

https://github.com/CeeJayCee/SilverbackIntegrationTest/pull/1

There wasn't actually any major issue. You just were using different topic names in consumer and producer.

**Comment by CeeJayCee** [comment]
Many thanks @BEagle1984. 

I have fixed the issue.

I performed a diff between the solution in https://github.com/CeeJayCee/SilverbackIntegrationTest and my real project.

I discovered that the solution provided in #139 was actually causing the problem. The call to WaitUntilConnectedAsync() was never completing successfully. 
Removing the broker callback to create the topics on-the-fly allows my tests to pass.
