### ISSUE TITLE
how do perform health check?

### ISSUE THREAD

**Issue by MohMehrnia** [BEagle1984/silverback#147]
how do perform health check?

**Comment by BEagle1984** [comment]
Can you elaborate a bit? What do you want to check?
Have you seen the documentation (https://silverback-messaging.net/concepts/broker/connecting.html#health-monitoring)?

**Comment by MohMehrnia** [comment]
i need health checked in console app or winforms

**Comment by MohMehrnia** [comment]
server health check status
i need check server is live or not

**Comment by MohMehrnia** [comment]
/api/healthchecks/node

**Comment by BEagle1984** [comment]
But what do you want to check? Which "server"?
The documentation isn't helpful?
All the implemented health checks are documented but there is no such thing as checking whether the "server" (I assume you mean the message broker here) is up&running.
The message broker itself should expose such health check.
Silverback can just try to figure out whether the consumers are connected with the message broker (`AddConsumersCheck`) or ensure that you can produce (`AddOutboundEndpointsCheck`). Note that in order to check the producers a "ping" message will be sent, your consumers have to ignore it.
