### ISSUE TITLE
Feature Request: RabbitMQ Direct Reply-To (RPC)

### ISSUE THREAD

**Issue by MarcoCestari** [BEagle1984/silverback#156]
Without going into the merits of whether it's an anti-pattern or not, is there any plans to support RabbitMQ RPC?

I couldn't find an way to implement it via behaviors.

[Direct Reply-to](https://www.rabbitmq.com/direct-reply-to.html)

**Comment by BEagle1984** [comment]
No, at the moment there isn't any plan to extend the RabbitMQ support any further.

As you might have noticed if you explored it a bit, the Silverback.Integration.Rabbit package has been left a little behind and doesn't get as much attention as Kafka and MQTT.
This is because I personally don't use RabbitMQ on production myself and I don't have the time nor the energy to push it forward just for the sake of it. I also don't feel super confident about it, not being able to test it on real applications.

This might even lead to the Rabbit support being discontinued in one of the next major versions unless somebody jumps in and is willing to put in some work to keep it alive and up-to-date with the other two brokers.
