### ISSUE TITLE
Silverback messages not published to the correct Kafka Topic

### ISSUE THREAD

**Issue by elialombardi** [BEagle1984/silverback#183]
I am using Apache Kafka as the message broker.

I have a two message classes:

- Animal (base class) which is published to / consumed from the "animals" Kafka topic
- Dog (extends Animal, but doesn't have any additional property) which is published to / consumed from the "dogs" Kafka topic

When I publish the message of type Dog, Silverback publishes two messages: one message in "animals" and another message in "dogs".

I was expecting the message of type Dog to be published only on the "dogs" topic.

**Comment by BEagle1984** [comment]
That's intentional. Silverback allows you to publish all animals to the same topic and uses a header to reinstantiate the correct type on the consumer side. I think this use case, where you want to send different messages through the same topic, is far more common than yours. If I wouldn't super polymorphism you'd need to define an outbound endpoint for each animal, even if producing to the same topic.

It's currently not possible to change this behavior and there's no built-in way to filter the outbound messages (this will probably be added to the next big major version).

Tour case can be covered with a topic name resolver though.

```csharp
.ProduceTo(envelope => 
   {
      if (envelope.Message is Dog)
         return "dogs";
      else
         return "other-animals";
   })
```

See https://silverback-messaging.net/concepts/broker/outbound-routing.html#endpoint-name-resolver for details.
