### ISSUE TITLE
Default Settings of JsonMessageSerializer

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#54]
The JsonMessageSerializer has "DefaultValueHandling" and "NullValueHandling" set to ignore. This is unfortunate because it is not possible to distinguish if a Nullable<ValueType> was null or had the default value.

E.g. `public bool? MyFlag;` can be true, false and null but false and null will not be serialized.

Whats the idea behind the DefaultValueHandling?

**Comment by BEagle1984** [comment]
Are you sure this is an issue?

In your example with the nullable bool:
* null (that is also the default) will be ignored (omitted in the JSON)
* true and false will be outputted as true/false (since they are neither null, nor the default value)

Oh well, this is what I would expect at least.

**Comment by msallin** [comment]
You are right. I just tested that.

Anyway, the reason I discovered it is a different one. As you know, we generate C# Code out of TypeScript-Type definitions (Apikana) . We have a case where we have properties which are marked as required there and they are value types. The code generator adds an attribute to the property "Required=Always". 

On the producer side we use Silverback with the default serializer. This will serialize this object without default values. On the consumer side we aren't able to deserialize because of this combination (it will throw a validation exception, as a required attribute isn't present). I guess this scenario will happen a lot. We can adjust our code generation but is it correct to not validate required fields? Wdyt?

**Comment by BEagle1984** [comment]
By default I skip null and default values to save some bytes, at the cost of potential interoperability issues.

Whether it’s correct to enforce the property to be always passed in the JSON, it’s a matter of opinion. I personally believe it doesn’t add anything to the message to have the default value being explicitly written. If for example an API with 20 boolean option flags is exposed, we could argue that the message is actually clearer and more readable if only the few flags with value true are passed.

Another story is to validate actual required fields, let’s say for instance a “Quantity” field. But in that case this discussion doesn’t matter because 0 wouldn’t be valid anyway.

I’m not familiar with Apikana myself. Could you share a snippet of a generated message model and explain me how (and where) does the validation take place? I wonder if there is a way to infer the proper settings on the producer side, according to the model and its attributes.

**Comment by msallin** [comment]
As this probably something more internal, lets discuss this after your holidays offline. We implemented a workaround and I close this issue for now.
