### ISSUE TITLE
Discussion: Management of Consumers

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#81]
Hi Sergio

We currently have the situation where we decide how to deal with error conditions. Most likely we will cover a bunch of known scenarios with skips and retires. However, if something unknown happens, we will always fail i.e. stop the consumer. 

Maybe there is an app with multiple consumers and just one is stopped. So bascially, the app still works fine. Until now we only see that a consumer was stopped, in the logs (of course we send alarms but thats more an event than a state). And the only thing we can to to reenable the consumer is to restart the whole app i.e. container.

1. Is it possible to detect the stopped consumer (e.g. Asp.net core HealthCheck -> Degreeded)
2. I would like to offer a management interface. In the simplest case, the consumer can be restarted. In more complex cases, this can be combined with "start, skip this message and continue". 
Thinking this further would lead to a API where you can ask for consumer status and start/stop a consumer.

Wdyt? Is it even possible at all? Is it compatible with the framework? What are the options?

**Comment by BEagle1984** [comment]
Hey

This is surely an interesting topic. I've already imagined that it would be of some interest to track the consumers state. It should also be fairly easy to implement a basic version since the `IBroker` implementation (e.g. the `KafkaBroker`) is holding a reference to all instantiated consumers already. Out of the box you can already resolve the `IBroker`, get all consumer instances and check whether they are in a connected state.
Going a bit further it would be very easy to build a singleton service that just focuses on tracking the consumers state, so that we offer a few extra information like last consumed message, errors and exception information, etc.
I actually wanted to implement something similar a while back, exactly to be able to create an health check based on this information.

Restarting the consumer is also not a problem at all. It is somewhat meant to be possible to disconnect and reconnect a consumer to sort of pause it. It is just never been used so far. In the `KafkaConsumer` I even dispose and re-instantiate the underlying consumer (Confluent) when an exception is thrown by its `Consume` method. (I know that it is often an unnecessary overreaction, but I preferred to do the safest thing possible to be sure to be able to recover from the weird and random errors that happen from time to time.)

I believe that a basic management API can be built without much effort and just some minor adjustments. With _basic_ I mean just to let you query the consumers status and start/stop them.

I see also that there might be the need of skipping a message and/or reposition the offset. It all can be done, but we need a clear prioritized requirements list.

Adding a UI is of course a different matter that would require a greater effort and I would postpone it a bit.

----

All this being said, are you sure that you really need to get the consumer to be stopped when a message cannot be processed? And how often is this supposed to happen?
If the message ordering isn't crucial I would just move the bad message in another topic after a few retry and log a critical. It is then quite easy to add a flag in your code to start processing that topic as well, that can be used to retry those messages after a fix has been done or to finally skip them.
I know, also this logic could be reused, but I'm hesitant into building these into Silverback as it is very unlikely that one size would fit all. What I provide are the error policies you can use to build your logic, retrying, skipping or moving messages.

**Comment by BEagle1984** [comment]
A small addition..

# Tasks and priorities

These are the very first tasks I could foresee, in order of priority:
1. New health check based on the consumer status (you can use it to mark the service as _degraded_ when a consumer gets stopped)
1. (REST) API to stop and start a consumer (cannot be used to create a new consumer, just to stop and re-start the existing ones) and in case disconnect/re-connect the entire broker (affecting all consumers)
1. (REST) API to query the consumers status, enriched with some additional details such as error and exceptions details, last consumed message information and possibly Kafka specific information such as assigned partitions.

Other stuff would need to be carefully analyzed to ensure they fit well into Silverback and are flexible enough.

# Skipping messages

This is easy to do if using the `DbOffsetStore` as you could simply modify the related record and have Silverback skip the messages until that offset. An API could be built to expose this possibility in a convenient way.

# Offset reset

Resetting the offset on the other hand is something I don't know if it fits into Silverback or it's a capability that you would expect on the message broker itself. (In fact we actually have some management API being exposed by our shared Kafka platform that would allow you to do that already.)

By the way, in Silverback you already have the possibility to reset the offset. This is properly done in the `KafkaPartitionAssignedEvent` handler, as documented here: https://beagle1984.github.io/silverback/docs/kafka/events#setting-starting-offsets-on-partitions-assignment. On top of this you can easily implement your custom logic to reset the offset according to a configuration setting.

**Comment by msallin** [comment]
> Restarting the consumer is also not a problem at all. It is somewhat meant to be possible to disconnect and reconnect a consumer to sort of pause it.
The Kafka Consumer event supports this. It is possible to pause (i.e. partitions stay assigned but are not consumed anymore). Maybe it makes sense to distinguish between stop (dispose) and pause (stop consuming i.e. do not disconnect and do not revoke partitions).

> With basic I mean just to let you query the consumers status and start/stop them.
I guess this is already very good.

>  It all can be done, but we need a clear prioritized requirements list.
As always.. :)

The first three tasks already sound very promising. I even don't expect the Web/Rest API from Silverback. This can be done later e.g. we can build it in our project, test it a bit and contribute it back. 

Btw. what is all covered with the not connected consumer. What happens, if a topic not exists for example? (you remember our HealthCheck discussion).

> Skipping Messages
We currently do not store the Offset in the Db. But this can be done with the offset reset. I can imagine something like: 
1. Set the offset on partition assigment, to be used next.
2. Restart the consumer (stop i.e. dispose and start).
This way messages can be skipped. 

Maybe it is helpfule if I elaborate a bit about the use cases behind all of this. As you know, we have a product which runs 24/7, whit peaks mainly outside of office hours. If it doesn't run, the consequences are huge. Thus, our operations team need corresponding tools, to judge the situation and e.g. accept data loss in order to be able to continue. Furthermore, as you know, we run on K8s and I would like to not use platform functionality for operations tasks (e.g. not restart the container to restart the consumer or to change a configuration). 

Beside of the management functionality, we do heavy investments in observability. Thus the HealthCheck. IMHO it should be visible at several places, if one of our services doesn't behave like it should. I.e. Logging, Tracing, HealthChecks, Metrics & Management Interface(s).

**Comment by msallin** [comment]
Random note: I think about the API. Maybe we can use IOptions. https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.ioptionsmonitor-1?view=dotnet-plat-ext-3.1

Would be cool to be able to start a service but disable the consumer already by using an env variable but react to changes - not care from where they come.

**Comment by BEagle1984** [comment]
It's a good idea but how would you push the changes into the `IOption` being monitored?

I'll actually have to think about this because it is a a bit more complex and has implications to the way we configure the endpoints. For example now we don't have a unique identifier for the endpoint / consumer to allow to properly combine the values from the `IOption` with the configuration provided via `AddInbound`.

----

For a first step I suggest to try and stick to what we already have available.

The `IBroker` already exposes the collection of `IConsumer` and that interface declares the `Connect` and `Disconnect` methods already.
So it is theoretically possible to connect/disconnect a single consumer already. It has of course to be tested since it is very possible that something doesn't work properly (this wasn't an intended use case so far).

What's missing is just to expose the `IsConnected` property and maybe some simple diagnostic information, as said already.

Setting the offset is also possible already via partitions assigned event.

**Comment by BEagle1984** [comment]
The enhanced consumer management API has been included in 3.0.0-beta.2
