### ISSUE TITLE
Support SourceLink.GitHub

### ISSUE THREAD

**Issue by alefcarlos** [BEagle1984/silverback#91]
What do you think about adding support to Source Link to enable debbuging Silverback?

https://github.com/dotnet/sourcelink

**Comment by BEagle1984** [comment]
Absolutely! I never did it but I guess it just requires a couple of extra parameters to `dot net pack`.

I never looked into it because I’m so used to debug the decompiled code with R#/Rider. I didn’t even realized this was a thing (NuGet is actually giving an hint when pushing a package without the symbols...but we all know that nobody pays close attention to the output).

Good idea. Will do for 3.0.

**Comment by 1bberto** [comment]
it would be great!!
Last week I had to debug the lib with my application and it wasn't easy.
I had to download the whole repo and add it to my application.

**Comment by BEagle1984** [comment]
Implemented and published with 3.0.0-beta.1
